apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-secret
data:
  postgres-username: {{ .Values.secret.postgres_username | b64enc | quote }}
  postgres-password: {{ .Values.secret.postgres_password | b64enc | quote }}